[package]
name = "knobify"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
dotenv = "0.15.0"
futures = "0.3.31"
rdev = "0.5.3"
rspotify = "0.14.0"
tokio = { version = "1.43.0", features = ["full"] }
tray-icon = "0.20.0"
webbrowser = "1.0.3"
winit = "0.30.9"
